// This file was generated by script

import chevronDown from './chevron-down.svg';
import notFound from './not-found.svg';
import twitter from './twitter.svg';

const icons = {
  'chevron-down': chevronDown,
  'not-found': notFound,
  twitter,
};

export default icons;
