// This file was generated by script

import arrowNext from './arrow-next.svg';
import arrowPrev from './arrow-prev.svg';
import bulb from './bulb.svg';
import defi from './defi.svg';
import discord from './discord.svg';
import email from './email.svg';
import generalVoting from './general-voting.svg';
import github from './github.svg';
import guilds from './guilds.svg';
import identityVoting from './identity-voting.svg';
import investment from './investment.svg';
import medium from './medium.svg';
import member from './member.svg';
import nftVoting from './nft-voting.svg';
import notFound from './not-found.svg';
import ownershipVoting from './ownership-voting.svg';
import projects from './projects.svg';
import reddit from './reddit.svg';
import social from './social.svg';
import twitter from './twitter.svg';
import voting from './voting.svg';

const icons = {
  'arrow-next': arrowNext,
  'arrow-prev': arrowPrev,
  bulb,
  defi,
  discord,
  email,
  'general-voting': generalVoting,
  github,
  guilds,
  'identity-voting': identityVoting,
  investment,
  medium,
  member,
  'nft-voting': nftVoting,
  'not-found': notFound,
  'ownership-voting': ownershipVoting,
  projects,
  reddit,
  social,
  twitter,
  voting,
};

export default icons;
