// This file was generated by script

import bulb from './bulb.svg';
import discord from './discord.svg';
import email from './email.svg';
import github from './github.svg';
import reddit from './reddit.svg';
import twitter from './twitter.svg';

const icons = {
  bulb,
  discord,
  email,
  github,
  reddit,
  twitter,
};

export default icons;
