const path = require('path');
const fs = require('fs');
const camelCase = require('camelcase');

const iconsPath = path.resolve(__dirname, '..', 'icons');

const getName = name => name.split('.')[0];

const getCamelCaseName = name => camelCase(getName(name));

const getImportLine = fileName =>
  `import ${getCamelCaseName(fileName)} from './${fileName}';`;

const getExportLine = fileName => {
  if (fileName.includes('-')) {
    return `  '${getName(fileName)}': ${getCamelCaseName(fileName)},`;
  }
  return `  ${getName(fileName)},`;
};

const svgFiles = fs.readdirSync(iconsPath).filter(file => file.endsWith('svg'));

// generate import data
const importData = svgFiles.map(getImportLine);

// generate export data
const exportData = svgFiles.map(getExportLine);

const data = [
  '// This file was generated by script',
  '',
  ...importData,
  '',
  'const icons = {',
  ...exportData,
  '};',
  '',
  'export default icons;',
  ''
];

fs.writeFileSync(path.resolve(iconsPath, 'index.ts'), data.join('\n'), {
  encoding: 'utf-8'
});
